admin_change_log_list:
    pattern:  /{page}
    defaults: { _controller: "AdminBundle:ChangeLog:list", page: 1 }
    requirements:
        page:  \d+

admin_change_log_filter:
    pattern:  /filter
    defaults: { _controller: "AdminBundle:ChangeLog:filter" }

admin_change_log_show:
    pattern:  /{id}/show
    defaults: { _controller: "AdminBundle:ChangeLog:show" }

admin_change_log_new:
    pattern:  /new
    defaults: { _controller: "AdminBundle:ChangeLog:new" }

admin_change_log_create:
    pattern:  /create
    defaults: { _controller: "AdminBundle:ChangeLog:create" }
    requirements: { _method: post }

admin_change_log_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AdminBundle:ChangeLog:edit" }

admin_change_log_update:
    pattern:  /{id}/update
    defaults: { _controller: "AdminBundle:ChangeLog:update" }
    requirements: { _method: post }

admin_change_log_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AdminBundle:ChangeLog:delete" }
