language: php

php:
    - 5.3.2
    - 5.3
    - 5.4

before_script:
    - cp app/config/parameters.ini.test app/config/parameters.ini
    - wget -nc http://getcomposer.org/composer.phar
    - php composer.phar install
    - ./bin/travis

script: phpunit -c app/

notifications:
    email:
        - mewt@madalynn.eu
