language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - cp app/config/parameters.yml.test app/config/parameters.yml
    - wget -nc http://getcomposer.org/composer.phar
    - php composer.phar install --prefer-dist --dev
    - ./bin/travis

branches:
    only:
        - master
        - develop

script: phpunit -c app/

notifications:
    email:
        - mewt@madalynn.eu
