language: php

php:
    - 5.3
    - 5.4

before_script:
    - cp app/config/parameters.ini.test app/config/parameters.ini
    - php bin/vendors install
    - ./bin/travis

script: phpunit -c app/

branches:
    only:
        - master

notifications:
    email:
        - mewt@madalynn.eu
    irc:
        - "irc.epiknet.org#androirc"
