homepage:
    pattern: /
    defaults: { _controller: AndroBundle:Main:homepage }

contact:
    pattern: /contact
    defaults: { _controller: AndroBundle:Main:contact }

eula:
    pattern: /eula
    defaults: { _controller: AndroBundle:Main:eula }

article_show:
    pattern: /article/{id}/{slug}
    defaults: { _controller: AndroBundle:Article:show }