homepage:
    pattern: /
    defaults: { _controller: AndroBundle:Main:homepage }

contact:
    pattern: /contact
    defaults: { _controller: AndroBundle:Main:contact }

eula:
    pattern: /eula
    defaults: { _controller: AndroBundle:Main:eula }

donate:
    pattern: /donate
    defaults: { _controller: AndroBundle:Main:donate }

article_show:
    pattern: /article/{id}/{slug}
    defaults: { _controller: AndroBundle:Article:show }

article_atom:
    pattern: /articles/atom
    defaults: { _controller: AndroBundle:Article:atom, _format: atom }

beta:
    pattern: /beta
    defaults: { _controller: AndroBundle:Beta:show }

beta_download:
    pattern: /beta/download
    defaults: { _controller: AndroBundle:Beta:download }