homepage:
    pattern: /
    defaults: { _controller: AndroBundle:Main:homepage }

contact:
    pattern: /contact
    defaults: { _controller: AndroBundle:Main:contact }

archives:
    pattern: /archives/{page}
    defaults: { _controller: AndroBundle:Article:archives, page: 1 }

eula:
    pattern: /eula
    defaults: { _controller: AndroBundle:Main:eula }

screenshots:
    pattern: /screenshots
    defaults: { _controller: AndroBundle:Main:screenshots }

donate:
    pattern: /donate
    defaults: { _controller: AndroBundle:Main:donate }

article_show:
    pattern: /article/{id}/{slug}
    defaults: { _controller: AndroBundle:Article:show }

article_atom:
    pattern: /articles/atom
    defaults: { _controller: AndroBundle:Article:atom, _format: atom }

beta:
    pattern: /beta
    defaults: { _controller: AndroBundle:Beta:show }

beta_download:
    pattern: /beta/download
    defaults: { _controller: AndroBundle:Beta:download }

tip:
    pattern: /tip/{lang}/{date}
    defaults: { _controller: AndroBundle:Main:tip, date: null }