imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true

# PlumBundle Configuration
madalynn_plum:
    deployers:
        - Plum\Deployer\RsyncDeployer
    servers:
        bender:
            host: bender.madalynn.eu
            user: web
            dir:  /home/web/androirc.com/www
            port: 2222
            options:
                rsync_exclude: "%kernel.root_dir%/config/rsync_exclude.txt"