imports:
    - { resource: parameters.yml }

framework:
    secret: %secret%
    esi: false
    translator: { enabled: true, fallback: en }
    default_locale: %locale%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    trust_proxy_headers: true
    templating:
        engines: ['twig']
        assets_version: 0efc94639b65f71c2652dcf394ba52145b52aa7c
        assets_version_format: %%s?v=%%s
    session:
        cookie_lifetime: 72000

security:
    providers:
        main:
            entity: { class: Madalynn\Bundle\MainBundle\Entity\User, property: username }
    encoders:
        Madalynn\Bundle\MainBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        security:
            pattern: /admin/login$
            security: false

        admin:
            pattern: /admin
            form_login:
                login_path: login
                use_forward: false
                check_path: login_check
                failure_path: null
            logout:
                path: logout
            anonymous: false
            remember_me:
                key: %secret%
                lifetime: 3600
                path: /
                domain: ~

    access_control:
        - { path: '/admin', role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'form_div_layout.html.twig'
            - 'MainBundle:Form:fields.html.twig'

assetic:
    debug: %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.6.jar
        yui_js:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.6.jar

doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        charset: UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    string_functions:
                        year: DoctrineExtensions\Query\Mysql\Year
                        month: DoctrineExtensions\Query\Mysql\Month

swiftmailer:
    transport: mail

jms_i18n_routing:
    default_locale: en
    locales: [en, fr, ko, pt, cs, zh, de, pl, fi, es, it, nl, el, tr]
    strategy: prefix_except_default
    cookie:
      enabled: false

white_october_pagerfanta:
    default_view: twitter_bootstrap_translated

sensio_framework_extra:
    request: { converters: false }

bazinga_geocoder:
    providers:
        free_geo_ip: ~
