imports:
    - { resource: parameters.ini }

framework:
    secret:          %secret%
    translator:      { fallback: en }
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    session:
        default_locale: %locale%
        auto_start:     true

# Security Configuration
security:
    providers:
        main:
            entity: { class: Madalynn\AndroBundle\Entity\User, property: username }
    encoders:
        Madalynn\AndroBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      .*
            form_login:
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:       true
            anonymous:    true
            remember_me:
                key:      %secret%
                lifetime: 3600
                path:     /
                domain:   ~
    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'AndroBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    java:           %java_path%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.6.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  mail

# AkismetBundle Configuration
ornicar_akismet:
    api_key: %akismet_api_key%
    url:     http://www.androirc.com

# AdmobBundle Configuration
madalynn_admob:
    publisher_id: a14de4eeeb0ee01
    analytics_id: a14debd8eddb7a3
    analytics_request: true

# DeployBundle Configuration
madalynn_deploy:
    servers:
        bender:
            host: bender.madalynn.eu
            user: web
            dir: /home/web/androirc.com/beta

# GravatarBundle Configuration
gravatar:
    size: 50