imports:
    - { resource: parameters.ini }

framework:
    secret:          %secret%
    translator:      { enabled: true, fallback: en }
    default_locale:  %locale%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines:               ['twig']
        assets_version:        2012031801
        assets_version_format: %%s?v=%%s
    session:
        auto_start:      true
        cookie_lifetime: 72000

# Security Configuration
security:
    providers:
        main:
            entity: { class: Madalynn\Bundle\AndroBundle\Entity\User, property: username }
    encoders:
        Madalynn\Bundle\AndroBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      .*
            form_login:
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:       true
            anonymous:    true
            remember_me:
                key:      %secret%
                lifetime: 3600
                path:     /
                domain:   ~
    access_control:
        - { path: ^(/.*)?/admin/, role: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'form_div_layout.html.twig'
            - 'AndroBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    java:           %java_path%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.6.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  mail

# AdmobBundle Configuration
madalynn_admob:
    publisher_id: a14eb7d2147c5a9
    textcolor: '026995'

# i18n Routing Configuration
jms_i18n_routing:
    default_locale: en
    locales: [en, fr, cs]
    strategy: prefix_except_default