imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true

# DeployBundle Configuration
madalynn_deploy:
    bender:
        host: bender.madalynn.eu
        user: web
        dir:  /home/web/androirc.com/www
        port: 2222