# Dashboard
admin_dashboard:
    pattern: /
    defaults: { _controller: AdminBundle:Main:dashboard }

# Article
admin_base_article:
    resource: 'routing/article.yml'
    prefix:   /article

# Donator
admin_base_donator:
    resource: 'routing/donator.yml'
    prefix:   /donator