# Dashboard
admin_dashboard:
    pattern: /
    defaults: { _controller: AdminBundle:Main:dashboard }

# Article
admin_base_article:
    resource: 'routing/article.yml'
    prefix:   /article

# Donator
admin_base_donator:
    resource: 'routing/donator.yml'
    prefix:   /donator

# Beta Release
admin_base_beta_release:
    resource: 'routing/beta_release.yml'
    prefix:   /beta

# User
admin_base_user:
    resource: 'routing/user.yml'
    prefix:   /user